# Generated by Django 2.1.7 on 2019-03-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=3)),
                ('books', models.CharField(max_length=70)),
                ('number_of_books', models.IntegerField(max_length=4)),
            ],
        ),
    ]
